# Change this asap
session:
  secret_key: "secret" # Generate with: openssl rand -base64 32
  cookie_name: "N0CTURNALBBS" # Name this whatever
  max_age: 86400 # 1 day in seconds
  secure: false # Set to true in production with HTTPS
  http_only: true
  same_site: "lax" # Options: strict|lax|none

    # CSRF Protection Settings
  csrf:
    secret: "secret" # Generate with: openssl rand -base64 32
    error_message: "Invalid security token."