# Important site descriptions
site:
  title: "N0CTURNALBBS"
  tagline: "Systems online. It's all good here."
  description: "Built on the stuff of nightmares."
  greeting: "Welcome, stranger."
  footer_text: "Powered by N0CTURNALBBS v1"